# syntax=toml

[options]
preset_column_widths = [ 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.50, 0.66 ]
animation_speed = 50
auto_center = false
sliver_width = 20
focus_follows_mouse = false
mouse_follows_focus = false

[bindings]
window_resize = "ralt - g"
window_shrink = "ralt - s"
window_focus_west = ["ralt - j", "ralt - leftarrow"]
window_focus_east = ["ralt - l", "ralt - rightarrow"]
window_focus_north = ["ralt - i", "ralt - uparrow"]
window_focus_south = ["ralt - k", "ralt - downarrow"]
window_focus_first = "ralt - y"
window_focus_last = "ralt - p"
window_swap_west = "ralt - u"
window_swap_east = "ralt - o"
window_swap_north = "ralt - z"
window_swap_south = "ralt - x"
window_center = "ralt - c"
window_fullwidth = "ralt - f"
window_manage = "ralt - t"
window_stack = "ralt - ["
window_unstack = "ralt - ]"
window_equalize = "ralt - e"
window_nextdisplay = "ralt - v"
mouse_nextdisplay = "ralt - b"
quit = "ralt - q"

[decorations.inactive.dim]
opacity = -0.05

[decorations.active.border]
enabled = true
color = "#A15D73"
width = 2.0
radius = "auto"

[swipe]
sensitivity = 0.2
deceleration = 10.0

[swipe.gesture]
fingers_count = 4
direction = "Natural"

[swipe.scroll]
modifier = "lalt"

[windows.all]
title = ".*"
horizontal_padding = 0

[windows.rider]
title = "Rollback Changes|Welcome to JetBrains Rider|^Settings$|Create: File|Add File to Git"
bundle_id = "com.jetbrains.rider"
floating = true

